import { getPosts } from '@/lib/post'
import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

interface HomeProps {
  posts: Post[]
}

const Home: NextPage<HomeProps> = ({ posts }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section style={{display: 'flex', flexDirection: 'column'}}>
          {posts.map((post) => (
            <article key={post.id}>
              <Link href={`/${post.id}`} passHref>
                <a role="article">
                  <h1>{post.frontMatter.title}</h1>
                </a>
              </Link>
              <span>{post.frontMatter.date}</span>
              <p>{post.frontMatter.description}</p>
            </article>
          ))}
        </section>
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const posts = getPosts();
  return { props: { posts } };
}

export default Home
