import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
  const posts = [
    { id: '1', title: '1', description: '1111'},
    { id: 'test', title: 'test', description: 'testest'},
    { id: '테스트', title: '테스트', description: '테스트테스트'},
  ]
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
      </nav>

      <main>
        <section style={{display: 'flex', flexDirection: 'column'}}>
          {posts.map((post) => (
            <article key={post.id}>
              <Link href={`/${post.id}`} passHref>
                <a role="article">
                  <h1>{post.title}</h1>
                </a>
              </Link>
              <p>{post.description}</p>
            </article>
          ))}
        </section>
      </main>

      <footer>
        footer
      </footer>
    </div>
  )
}

export default Home
